### ISSUE TITLE
Cursor end position for arrow function snippets

### ISSUE THREAD

**Issue by alexey-kozlenkov** [t7yang/vscode-hyper-javascript-snippets#1]
Hey @t7yang, seems like you've [recently updated several function snippets](https://github.com/t7yang/vscode-hyper-javascript-snippets/commit/2b9c2e14f0bb4b16dc45472c51d4b423687450a2#diff-a8d5941dde52676bebd786288a66db62) to place cursor end position correctly.
Any reason why arrow function snippets have been missed?
```
"arrow function (ES2015)": {
  "prefix": "af",
  "body": "(${1}) => ${2}",
  "description": "arrow function (ES2015)"
},
"async arrow function (ES2015)": {
  "prefix": "afa",
  "body": "async (${1}) => ${2}",
  "description": "async arrow function (ES2015)"
},
```
I can quickly submit a PR for this if needed.

**Comment by t7yang** [comment]
thx @alexey-kozlenkov for remind me.
I do a review (c5aa31b9310bd67dd905deb38c4a805e5f0c484c) and make sure all snippets end with `${0}`.
