### ISSUE TITLE
`function` snippets should/n't with parentheses?

### ISSUE THREAD

**Issue by t7yang** [t7yang/vscode-hyper-javascript-snippets#4]
Moving across parentheses lose all tabstop happen occasionally, it is [intended](https://github.com/Microsoft/vscode/issues/32790#issuecomment-323655481).

But Idk the details about the conditionals to escape tabstop.

If parentheses input by user.

This is fine:
```ts
(foo)|: string => |
     ^
```

But this lose tabstop:
```ts
(foo: string)| => 
             ^
```

if parentheses generate by user, then moving across parentheses 100% lose tabstop...

I probably switch back to generate `()` and add more tabstop to fit requirement for generic types and generator function :(

Any feedback, please comment below.

**Comment by alexey-kozlenkov** [comment]
Hey 👋 
Any chances to move newly added snippets for arrow function for TS to a new name? 
Perhaps `af` for TS -> `aft` (arrow function typed) / `taf` (typed arrow function)

Bringing this up cause i.e. `af` changed and now requires to press tab 4 times to get to function body instead of previous 2 times. (Personally I'm a lot muscle-memorized it and 3.1.0 update now brings frustration. )
Thanks!

**Comment by t7yang** [comment]
I was indecisive to this issue, very happy someone give me feedback.

What if:
`af` : `($1)$2 => $0` (should/shouldn't add `$2` for return type? click 2 times to get to function body)
`afg` : `$1($2)$3 => $0` (new, g stand for generic/generator maybe arrow generator function in future)

**Comment by alexey-kozlenkov** [comment]
I'd go with an option 
- leave `af` as it was: plain "js" function (seems to me pretty often use-case for some callbacks where TS infers return type)
- add `afg` with `$1($2)$3 => $0` for any other use case when user need to provide generics/return type

In general, my point : having backward compatibility would be awesome. I personally use `af` like 50 times a day and very get used to it format. 
Having new snippet for typed one is good, however, in my opinion, shouldn't kill existing behavior. 🙏

**Comment by t7yang** [comment]
Finally, I provide four new snippets `ar`, `ara` (with return type), `ag`, `aga` (with generic and return type).

**Comment by alexey-kozlenkov** [comment]
Thanks for the efforts @t7yang!
